package com.shaft.intellij.project;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.FileAlreadyExistsException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.Optional;

/**
 * Writes a GitHub Actions workflow that runs a SHAFT project's tests headless and uploads its
 * Allure results (issue #6641). Never overwrites: an existing workflow file is left untouched.
 * <p>
 * Takes a {@link Path}, not a {@code Project}, so it is unit-testable against real temp files.
 */
public final class ShaftGithubWorkflowFile {
    /** Workflow location relative to the project root. */
    public static final String RELATIVE_PATH = ".github/workflows/shaft-tests.yml";

    /** Build tool the generated workflow drives. */
    public enum BuildTool {
        /** Maven project ({@code pom.xml}); uses {@code ./mvnw} when present, else {@code mvn}. */
        MAVEN,
        /** Gradle project with a committed Gradle wrapper ({@code gradlew}). */
        GRADLE
    }

    /** What {@link #generate(Path)} did. */
    public enum Outcome {
        /** The workflow file was written. */
        CREATED,
        /** A workflow file already exists; nothing was written. */
        ALREADY_EXISTS,
        /** No {@code pom.xml} and no Gradle wrapper at the project root; nothing was written. */
        UNSUPPORTED_BUILD
    }

    /**
     * Result of {@link #generate(Path)}.
     *
     * @param outcome what happened
     * @param file    the workflow path (whether or not it was written)
     */
    public record Result(Outcome outcome, Path file) {
    }

    private ShaftGithubWorkflowFile() {
        throw new IllegalStateException("Utility class");
    }

    /**
     * Writes {@link #RELATIVE_PATH} under {@code projectRoot} unless it already exists.
     *
     * @param projectRoot project root directory
     * @return the outcome and the workflow path
     * @throws IOException when the file cannot be written
     */
    public static Result generate(Path projectRoot) throws IOException {
        Path file = projectRoot.resolve(RELATIVE_PATH);
        if (Files.exists(file)) {
            return new Result(Outcome.ALREADY_EXISTS, file);
        }
        Optional<BuildTool> buildTool = detectBuildTool(projectRoot);
        if (buildTool.isEmpty()) {
            return new Result(Outcome.UNSUPPORTED_BUILD, file);
        }
        Files.createDirectories(file.getParent());
        try {
            // CREATE_NEW fails instead of overwriting if the file appeared since the check above.
            Files.writeString(file, render(buildTool.get(), Files.isRegularFile(projectRoot.resolve("mvnw"))),
                    StandardCharsets.UTF_8, StandardOpenOption.CREATE_NEW, StandardOpenOption.WRITE);
        } catch (FileAlreadyExistsException e) {
            return new Result(Outcome.ALREADY_EXISTS, file);
        }
        return new Result(Outcome.CREATED, file);
    }

    /**
     * Detects the build tool at {@code projectRoot}: Maven when {@code pom.xml} exists, else
     * Gradle when the {@code gradlew} wrapper exists.
     *
     * @param projectRoot project root directory
     * @return the build tool, or empty when neither is present
     */
    static Optional<BuildTool> detectBuildTool(Path projectRoot) {
        if (Files.isRegularFile(projectRoot.resolve("pom.xml"))) {
            return Optional.of(BuildTool.MAVEN);
        }
        if (Files.isRegularFile(projectRoot.resolve("gradlew"))) {
            return Optional.of(BuildTool.GRADLE);
        }
        return Optional.empty();
    }

    /**
     * Renders the workflow YAML.
     *
     * @param buildTool    build tool to drive
     * @param mavenWrapper whether a Maven project has {@code mvnw}
     * @return workflow file content
     */
    static String render(BuildTool buildTool, boolean mavenWrapper) {
        String cache = buildTool == BuildTool.MAVEN ? "maven" : "gradle";
        String run = switch (buildTool) {
            case MAVEN -> mavenWrapper ? "chmod +x mvnw && ./mvnw -B test" : "mvn -B test";
            case GRADLE -> "chmod +x gradlew && ./gradlew test --no-daemon";
        };
        return """
                # Generated by the SHAFT IntelliJ plugin. Runs SHAFT tests headless and uploads Allure results.
                name: SHAFT tests

                on:
                  push:
                  pull_request:
                  workflow_dispatch:

                permissions:
                  contents: read

                jobs:
                  test:
                    runs-on: ubuntu-latest
                    env:
                      # Reaches every JVM the build forks, including the test JVM.
                      JAVA_TOOL_OPTIONS: -DheadlessExecution=true
                    steps:
                      - uses: actions/checkout@v7.0.1
                      - uses: actions/setup-java@v6
                        with:
                          java-version: '25'
                          distribution: 'zulu'
                          cache: '%s'
                      - name: Run SHAFT tests
                        run: %s
                      - name: Upload Allure results
                        if: always()
                        uses: actions/upload-artifact@v7.0.1
                        with:
                          name: allure-results
                          path: allure-results
                          if-no-files-found: warn
                """.formatted(cache, run);
    }
}
