package com.shaft.capture.generate;

import com.shaft.capture.model.ElementSnapshot;
import com.shaft.capture.model.LocatorCandidate;
import com.shaft.gui.internal.locator.Locator;
import com.shaft.gui.internal.locator.Role;
import org.openqa.selenium.By;

import java.util.List;
import java.util.Locale;
import java.util.Optional;
import java.util.Set;
import java.util.regex.Pattern;

/**
 * Issue #4271: the single deterministic locator-selection policy for every SHAFT surface that
 * identifies an element from captured evidence.
 */
public final class LocatorPolicy {
    private static final Set<String> TAGS_WITHOUT_OWN_TEXT = Set.of("input", "textarea", "select");

    private LocatorPolicy() {
    }

    /**
     * Plans how {@code candidate} would be emitted for {@code target}.
     *
     * @param target the captured element
     * @param candidate one piece of captured locator evidence
     * @return the plan, or empty when the evidence is not trustworthy enough to emit
     */
    public static Optional<LocatorPlan> plan(ElementSnapshot target, LocatorCandidate candidate) {
        return idPlan(candidate)
                .or(() -> rolePlan(target, candidate))
                .or(() -> xpathPlan(candidate));
    }

    private static Optional<LocatorPlan> idPlan(LocatorCandidate candidate) {
        String id = candidate.expression();
        if (candidate.strategy() != LocatorCandidate.LocatorStrategy.ID
                || candidate.uniquenessCount() != 1
                || !candidate.stable()
                // LocatorBuilder.hasId interpolates the raw value into [@id="..."] unescaped, so a
                // value carrying a double quote would build a malformed XPath. Excluded here rather
                // than emitted broken; such an element still reaches the verified-XPath tier.
                || id.indexOf('"') >= 0
                || looksAutoGenerated(id)) {
            return Optional.empty();
        }
        return Optional.of(new LocatorPlan(
                Tier.UNIQUE_ID,
                "SHAFT.GUI.Locator.hasAnyTagName().hasId(\"" + javaString(id) + "\").build()",
                Locator.hasAnyTagName().hasId(id).build()));
    }

    /**
     * Tier 1 promotes an id above a live-verified ARIA role, so its premise -- that the id was
     * written by a human and will survive a redeploy -- has to be enforced here rather than assumed.
     * The recorder's own {@code stable} flag is not sufficient evidence: {@code dynamic()}
     * ({@code shaft-capture-recorder.js:17-19}) tests only for an 8+ digit run or a UUID, so every
     * shape below is reported stable, and candidates built directly in Java (the shaft-mcp adapters)
     * never run that check at all.
     *
     * <p>This is unavoidably a heuristic over an open set of frameworks and it will never be
     * complete. It is deliberately biased toward refusing: a false positive costs one tier (the
     * element still generates from its verified role or XPath), while a false negative ships a
     * locator that silently breaks on the next deploy. An ordinary authored id that happens to end
     * in {@code -<number>} is the known, accepted false positive.
     *
     * @param id the candidate id
     * @return whether the id looks framework-generated rather than authored
     */
    private static boolean looksAutoGenerated(String id) {
        return AUTO_GENERATED_ID_SHAPES.stream().anyMatch(shape -> shape.matcher(id).find());
    }

    private static final List<Pattern> AUTO_GENERATED_ID_SHAPES = List.of(
            Pattern.compile(":[A-Za-z0-9]+:"),                       // React useId, Radix
            Pattern.compile("-\\d+(?:-|$)"),                         // mat-input-3, react-select-2-input
            Pattern.compile("(?i)^ember\\d+$"),                      // Ember
            Pattern.compile("(?i)^j_idt\\d+"),                       // JSF
            Pattern.compile("(?i)^ctl\\d+_"),                        // ASP.NET WebForms
            Pattern.compile("(?i)^jss\\d+$"),                        // JSS, Material-UI v4
            Pattern.compile("(?i)^(?:radix|cdk|mat|sc|css|emotion)-"), // Radix, Angular, CSS-in-JS
            Pattern.compile("\\d{8,}"),                              // mirrors recorder dynamic()
            Pattern.compile("(?i)[a-f0-9]{8}-[a-f0-9-]{27,}"));      // mirrors recorder dynamic()

    private static Optional<LocatorPlan> xpathPlan(LocatorCandidate candidate) {
        String xpath = candidate.replayXpath();
        if (xpath.isBlank() || isAbsolute(xpath)) {
            return Optional.empty();
        }
        return Optional.of(new LocatorPlan(
                Tier.VERIFIED_XPATH,
                "By.xpath(\"" + javaString(xpath) + "\")",
                By.xpath(xpath)));
    }

    /**
     * Mirrors {@code GeneratedCodeGuardrails}' {@code ABSOLUTE_XPATH} rule, so that guardrail
     * becomes unreachable through this policy instead of merely catching its output.
     */
    private static boolean isAbsolute(String xpath) {
        String trimmed = xpath.trim();
        return (trimmed.startsWith("/") && !trimmed.startsWith("//")) || trimmed.startsWith("(/");
    }

    private static Optional<LocatorPlan> rolePlan(ElementSnapshot target, LocatorCandidate candidate) {
        if (candidate.strategy() != LocatorCandidate.LocatorStrategy.ROLE || !candidate.roleXpathVerified()) {
            return Optional.empty();
        }
        Role role = ariaRole(target.role());
        if (role == null) {
            return Optional.empty();
        }
        String name = semanticName(target, candidate);
        String prefix = "SHAFT.GUI.Locator.hasRole(Role." + role.name() + ")";
        if (name.isBlank() || !tagCanCarryOwnText(target.tagName())) {
            return Optional.of(new LocatorPlan(
                    Tier.VERIFIED_ROLE, prefix + ".build()", Locator.hasRole(role).build()));
        }
        return Optional.of(new LocatorPlan(
                Tier.VERIFIED_ROLE,
                prefix + ".hasNormalizedText(\"" + javaString(name) + "\").build()",
                Locator.hasRole(role).hasNormalizedText(name).build()));
    }

    /**
     * Issue #4239 P1.4a: input/textarea/select can never carry their own visible text, so pairing a
     * verified role with {@code hasNormalizedText} compiles but is unsatisfiable at replay.
     */
    private static boolean tagCanCarryOwnText(String tagName) {
        return !TAGS_WITHOUT_OWN_TEXT.contains(tagName.toLowerCase(Locale.ROOT));
    }

    private static String semanticName(ElementSnapshot target, LocatorCandidate candidate) {
        if (candidate.strategy() == LocatorCandidate.LocatorStrategy.ROLE
                && candidate.expression().contains(":")) {
            return candidate.expression().substring(candidate.expression().indexOf(':') + 1);
        }
        String name = target.accessibleName().isBlank() ? target.label() : target.accessibleName();
        return name.isBlank() ? candidate.expression() : name;
    }

    /**
     * Maps a raw ARIA role string to one of the 14 {@link Role} constants, case-insensitively,
     * including the known ARIA-name vs. enum-name mismatches. Returns {@code null} when the role has
     * no equivalent -- which is precisely why the mapping must be part of the tier decision.
     *
     * @param rawRole the captured role string
     * @return the mapped role, or {@code null} when unmappable
     */
    static Role ariaRole(String rawRole) {
        return switch (rawRole == null ? "" : rawRole.trim().toLowerCase(Locale.ROOT)) {
            case "button" -> Role.BUTTON;
            case "link" -> Role.LINK;
            case "textbox" -> Role.TEXTBOX;
            case "checkbox" -> Role.CHECKBOX;
            case "radio" -> Role.RADIO;
            case "combobox" -> Role.COMBOBOX;
            case "heading" -> Role.HEADING;
            case "img", "image" -> Role.IMAGE;
            case "list" -> Role.LIST;
            case "listitem" -> Role.LISTITEM;
            case "table", "grid" -> Role.TABLE;
            case "row" -> Role.TABLE_ROW;
            case "cell", "gridcell" -> Role.TABLE_CELL;
            case "columnheader" -> Role.TABLE_COLUMNHEADER;
            default -> null;
        };
    }

    private static String javaString(String value) {
        return value == null ? "" : value.replace("\\", "\\\\")
                .replace("\"", "\\\"")
                .replace("\r", "\\r")
                .replace("\n", "\\n")
                .replace("\t", "\\t");
    }

    /**
     * Emission tiers, most preferred first.
     */
    public enum Tier {
        /** A unique, stable, human-authored {@code id}. */
        UNIQUE_ID,
        /** A recorder-verified ARIA role that maps to a {@link Role} constant. */
        VERIFIED_ROLE,
        /** A native, relative, self-verified XPath the recorder resolved against the live DOM. */
        VERIFIED_XPATH
    }

    /**
     * How one candidate is emitted.
     *
     * @param tier the tier that admitted the candidate
     * @param source the Java source text to render
     * @param runtimeLocator the locator the rendered source resolves to at replay
     */
    public record LocatorPlan(Tier tier, String source, By runtimeLocator) {
    }
}
