package com.shaft.enums.internal;

public enum ElementAction {
    CLEAR, BACKSPACE, GET_TEXT, GET_CONTENT, GET_VALUE, SEND_KEYS, IS_DISPLAYED, SET_VALUE_USING_JAVASCRIPT, GET_ATTRIBUTE, HOVER, CLICK
}