#!/usr/bin/env python3
"""Generate and validate SHAFT skill inventory and quality evidence (#4640)."""

import argparse
import json
import re
from pathlib import Path

try:
    from scripts.ci.assemble_shaft_skills_plugin import package_path_for_source
    from scripts.ci.validate_agent_plugins import parse_skill_frontmatter
except ModuleNotFoundError:  # Direct script execution places scripts/ci on sys.path.
    from assemble_shaft_skills_plugin import package_path_for_source
    from validate_agent_plugins import parse_skill_frontmatter

ROOT = Path(__file__).resolve().parents[2]
SKILLS_DIRECTORY = "shaft-skills"
REVIEW_FILE = "quality-review.json"
INVENTORY_FILE = "INVENTORY.md"
QUALITY_FILE = "QUALITY.md"
QUALITY_DIMENSIONS = (
    "trigger_precision",
    "sibling_overlap",
    "dependency_depth",
    "reference_freshness",
    "runnable_evidence",
    "context_cost",
)
LINK = re.compile(r"\[[^]]*]\((?P<target>[^)]+)\)")


def _skills_root(root: Path) -> Path:
    return Path(root) / SKILLS_DIRECTORY


def _discover(root: Path) -> list[dict]:
    """Read directly discoverable skill metadata from canonical sources."""
    root = Path(root)
    skills_root = _skills_root(root)
    skills: list[dict] = []
    if not skills_root.is_dir():
        return skills
    for child in sorted(skills_root.iterdir(), key=lambda path: path.name):
        skill_path = child / "SKILL.md"
        if not child.is_dir() or not skill_path.is_file():
            continue
        content = skill_path.read_text(encoding="utf-8")
        frontmatter = parse_skill_frontmatter(content) or {}
        description = frontmatter.get("description", "")
        references: list[str] = []
        for match in LINK.finditer(content):
            target = match.group("target").strip().strip("<>")
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target = target.split("#", 1)[0].split("?", 1)[0]
            if target:
                try:
                    references.append((child / target).resolve().relative_to(skills_root.resolve()).as_posix())
                except (OSError, ValueError):
                    references.append(target)
        skills.append(
            {
                "name": child.name,
                "description": description if isinstance(description, str) else "",
                "canonical_path": skill_path.relative_to(root).as_posix(),
                "package_path": package_path_for_source(skills_root, skill_path).as_posix(),
                "references": sorted(set(references)),
                "line_count": len(content.splitlines()),
                "skill_path": skill_path,
                "content": content,
            }
        )
    return skills


def _load_review(root: Path) -> dict:
    path = _skills_root(root) / REVIEW_FILE
    try:
        review = json.loads(path.read_text(encoding="utf-8"))
    except (OSError, UnicodeDecodeError, json.JSONDecodeError):
        return {}
    return review if isinstance(review, dict) else {}


def _escape(value: object) -> str:
    return str(value).replace("|", "\\|").replace("\r", " ").replace("\n", " ")


def render_inventory(root: Path = ROOT) -> str:
    """Render the authoritative source-to-package inventory."""
    review = _load_review(root)
    package = review.get("package", "")
    clients = review.get("supported_clients", [])
    client_text = "; ".join(clients) if isinstance(clients, list) else ""
    lines = [
        "# SHAFT skill inventory",
        "",
        "Generated by `scripts/ci/shaft_skill_quality.py --write`; do not edit manually.",
        "",
        "| Skill | Canonical source | Package path | Package | Supported clients | Description | Linked local references |",
        "| --- | --- | --- | --- | --- | --- | --- |",
    ]
    for skill in _discover(root):
        references = "; ".join(skill["references"]) or "—"
        lines.append(
            "| {name} | `{canonical}` | `{package_path}` | {package} | {clients} | {description} | {references} |".format(
                name=_escape(skill["name"]),
                canonical=_escape(skill["canonical_path"]),
                package_path=_escape(skill["package_path"]),
                package=_escape(package),
                clients=_escape(client_text),
                description=_escape(skill["description"]),
                references=_escape(references),
            )
        )
    return "\n".join(lines) + "\n"


def render_quality_report(root: Path = ROOT) -> str:
    """Render reviewed quality scores alongside live context measurements."""
    review = _load_review(root)
    rows = review.get("skills", {})
    rows = rows if isinstance(rows, dict) else {}
    labels = [dimension.replace("_", " ").capitalize() for dimension in QUALITY_DIMENSIONS]
    lines = [
        "# SHAFT skill quality scorecard",
        "",
        "Generated by `scripts/ci/shaft_skill_quality.py --write`; scores are reviewed in `quality-review.json`.",
        "",
        "| Skill | " + " | ".join(labels) + " | Description characters | Confusion checks | Review notes |",
        "| --- | " + " | ".join(["---:"] * len(labels)) + " | ---: | --- | --- |",
    ]
    for skill in _discover(root):
        row = rows.get(skill["name"], {})
        row = row if isinstance(row, dict) else {}
        scores = row.get("scores", {})
        scores = scores if isinstance(scores, dict) else {}
        confusion = row.get("confusion_with", [])
        confusion_text = "; ".join(confusion) if isinstance(confusion, list) else ""
        values = [str(scores.get(dimension, "—")) for dimension in QUALITY_DIMENSIONS]
        lines.append(
            "| {name} | {scores} | {characters} | {confusion} | {notes} |".format(
                name=_escape(skill["name"]),
                scores=" | ".join(_escape(value) for value in values),
                characters=len(skill["description"]),
                confusion=_escape(confusion_text or "—"),
                notes=_escape(row.get("notes", "")),
            )
        )
    return "\n".join(lines) + "\n"


def write_generated(root: Path = ROOT) -> None:
    """Refresh both checked-in generated quality artifacts."""
    skills_root = _skills_root(root)
    skills_root.mkdir(parents=True, exist_ok=True)
    (skills_root / INVENTORY_FILE).write_text(render_inventory(root), encoding="utf-8")
    (skills_root / QUALITY_FILE).write_text(render_quality_report(root), encoding="utf-8")


def _integer_budget(budgets: dict, field: str, defects: list[str]) -> int | None:
    value = budgets.get(field)
    if not isinstance(value, int) or isinstance(value, bool) or value < 1:
        defects.append(f"quality-config: context_budget.{field} must be a positive integer")
        return None
    return value


def validate_repository(root: Path = ROOT) -> list[str]:
    """Return stable validation defects for the canonical SHAFT skill corpus."""
    root = Path(root)
    defects: list[str] = []
    skills_root = _skills_root(root)
    skills = _discover(root)
    skill_names = {skill["name"] for skill in skills}
    review = _load_review(root)
    if not review:
        return [f"quality-config: {SKILLS_DIRECTORY}/{REVIEW_FILE} must contain valid JSON"]

    package = review.get("package")
    clients = review.get("supported_clients")
    if not isinstance(package, str) or not package.strip():
        defects.append("quality-config: package must be a non-empty string")
    if not isinstance(clients, list) or not clients or not all(isinstance(client, str) and client for client in clients):
        defects.append("quality-config: supported_clients must contain non-empty strings")

    budgets = review.get("context_budget")
    if not isinstance(budgets, dict):
        budgets = {}
        defects.append("quality-config: context_budget must be an object")
    max_description = _integer_budget(budgets, "max_description_chars", defects)
    max_total = _integer_budget(budgets, "max_total_description_chars", defects)
    max_lines = _integer_budget(budgets, "max_skill_md_lines", defects)

    reviews = review.get("skills")
    if not isinstance(reviews, dict):
        reviews = {}
        defects.append("quality-config: skills must be an object")
    review_names = set(reviews)
    if review_names != skill_names:
        missing = ", ".join(sorted(skill_names - review_names)) or "none"
        unknown = ", ".join(sorted(review_names - skill_names)) or "none"
        defects.append(f"review-skill-set: missing [{missing}]; unknown [{unknown}]")

    for name in sorted(skill_names & review_names):
        row = reviews[name]
        if not isinstance(row, dict):
            defects.append(f"quality-row: {name} review must be an object")
            continue
        scores = row.get("scores")
        if not isinstance(scores, dict) or set(scores) != set(QUALITY_DIMENSIONS):
            defects.append(f"quality-dimensions: {name} must score exactly {', '.join(QUALITY_DIMENSIONS)}")
        else:
            for dimension, score in scores.items():
                if not isinstance(score, int) or isinstance(score, bool) or not 1 <= score <= 5:
                    defects.append(f"quality-score: {name}.{dimension} must be an integer from 1 to 5")
        confusion = row.get("confusion_with")
        if not isinstance(confusion, list) or not all(isinstance(item, str) for item in confusion):
            defects.append(f"confusion-skill: {name}.confusion_with must be an array of skill names")
        else:
            invalid = sorted(item for item in confusion if item not in skill_names or item == name)
            if invalid:
                defects.append(f"confusion-skill: {name} has invalid targets {', '.join(invalid)}")
        notes = row.get("notes")
        if not isinstance(notes, str) or len(notes.strip()) < 20:
            defects.append(f"quality-notes: {name} must record a substantive review note")

    total_description = 0
    skills_root_resolved = skills_root.resolve()
    for skill in skills:
        description_length = len(skill["description"])
        total_description += description_length
        if max_description is not None and description_length > max_description:
            defects.append(
                f"description-budget: {skill['name']} uses {description_length}/{max_description} description characters"
            )
        if max_lines is not None and skill["line_count"] > max_lines:
            defects.append(
                f"progressive-disclosure-budget: {skill['name']} uses {skill['line_count']}/{max_lines} SKILL.md lines"
            )
        for match in LINK.finditer(skill["content"]):
            target = match.group("target").strip().strip("<>")
            if not target or target.startswith(("#", "http://", "https://", "mailto:")):
                continue
            target = target.split("#", 1)[0].split("?", 1)[0]
            candidate = (skill["skill_path"].parent / target).resolve()
            try:
                candidate.relative_to(skills_root_resolved)
            except (OSError, ValueError):
                defects.append(f"linked-reference-containment: {skill['name']} link escapes shaft-skills: {target}")
                continue
            if not candidate.is_file():
                defects.append(f"linked-reference: {skill['name']} link does not resolve to a file: {target}")
    if max_total is not None and total_description > max_total:
        defects.append(f"listing-budget: descriptions use {total_description}/{max_total} characters")

    inventory_path = skills_root / INVENTORY_FILE
    quality_path = skills_root / QUALITY_FILE
    if not inventory_path.is_file() or inventory_path.read_text(encoding="utf-8") != render_inventory(root):
        defects.append(f"inventory-drift: refresh {SKILLS_DIRECTORY}/{INVENTORY_FILE} with --write")
    if not quality_path.is_file() or quality_path.read_text(encoding="utf-8") != render_quality_report(root):
        defects.append(f"quality-report-drift: refresh {SKILLS_DIRECTORY}/{QUALITY_FILE} with --write")
    return defects


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--write", action="store_true", help="refresh generated inventory and quality reports")
    arguments = parser.parse_args()
    if arguments.write:
        write_generated(ROOT)
    defects = validate_repository(ROOT)
    for defect in defects:
        print(f"error: {defect}")
    return 1 if defects else 0


if __name__ == "__main__":
    raise SystemExit(main())
