version: '3.8'

services:
  shaft-generator:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: shaft-project-generator
    ports:
      - "8080:8080"
    environment:
      - SERVER_PORT=8080
      - JAVA_OPTS=-Xmx512m -Xms256m
    volumes:
      - ./templates:/app/templates:ro
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8080/"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - shaft-network

networks:
  shaft-network:
    driver: bridge
