package testPackage.unitTests;

import com.shaft.gui.internal.locator.Locator;
import com.shaft.gui.internal.locator.LocatorBuilder;
import com.shaft.gui.internal.locator.Role;
import org.openqa.selenium.By;
import org.testng.Assert;
import org.testng.annotations.AfterMethod;
import org.testng.annotations.Test;

/**
 * Extended unit tests for {@link LocatorBuilder}, {@link Locator}, {@link Role}, and
 * {@code XpathAxis} covering builder methods not included in the existing
 * {@code LocatorBuilderUnitTest}.
 *
 * <p>All tests are pure Java (no browser required) and verify the xpath/css
 * expressions generated by the fluent builder API.
 */
public class LocatorBuilderExtendedUnitTest {

    @AfterMethod(alwaysRun = true)
    public void cleanupThreadLocals() {
        LocatorBuilder.cleanup();
    }

    // ─── containsAttribute ─────────────────────────────────────────────────────

    @Test(description = "containsAttribute: locator should embed contains(@ …) predicate in xpath")
    public void containsAttributeShouldBuildXpathContainsPredicate() {
        By locator = Locator.hasTagName("div").containsAttribute("class", "btn").build();
        Assert.assertNotNull(locator, "Locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("contains") && str.contains("btn"),
                "Built locator must use contains(@class, …) predicate and include the value");
    }

    @Test(description = "containsAttribute: value is embedded literally in the expression")
    public void containsAttributeValueShouldAppearInLocatorString() {
        By locator = Locator.hasAnyTagName().containsAttribute("data-id", "item-42").build();
        Assert.assertTrue(locator.toString().contains("item-42"),
                "The partial attribute value should be present in the locator string");
    }

    // ─── hasId / containsId ────────────────────────────────────────────────────

    @Test(description = "hasId: locator should contain the exact id in an @id predicate")
    public void hasIdShouldBuildExactIdPredicate() {
        By locator = Locator.hasTagName("input").hasId("username").build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("username"),
                "Exact id value should appear in the locator string");
    }

    @Test(description = "containsId: locator should use contains(@id, …) expression")
    public void containsIdShouldBuildContainsIdPredicate() {
        By locator = Locator.hasTagName("button").containsId("submit").build();
        Assert.assertNotNull(locator, "Locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("contains") && str.contains("submit"),
                "Locator must use contains(@id, …) and include the partial value");
    }

    // ─── hasClass / containsClass ──────────────────────────────────────────────

    @Test(description = "hasClass: locator should contain exact class predicate")
    public void hasClassShouldBuildExactClassPredicate() {
        By locator = Locator.hasTagName("div").hasClass("container").build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("container"),
                "Exact class name should appear in the locator string");
    }

    @Test(description = "containsClass: locator should use contains(@class, …) expression")
    public void containsClassShouldBuildContainsClassPredicate() {
        By locator = Locator.hasTagName("section").containsClass("col-").build();
        Assert.assertNotNull(locator, "Locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("contains") && str.contains("col-"),
                "Locator must use contains(@class, …) and include the partial class value");
    }

    // ─── hasIndex ──────────────────────────────────────────────────────────────

    @Test(description = "hasIndex: locator for index 3 should wrap expression in positional brackets")
    public void hasIndexShouldWrapExpressionWithPositionalBrackets() {
        By locator = Locator.hasTagName("tr").hasIndex(3).build();
        Assert.assertNotNull(locator, "Locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("[3]") || str.contains("3"),
                "Index 3 should appear in the locator expression");
    }

    @Test(description = "hasIndex: index 1 and isFirst() should produce equivalent locators")
    public void hasIndexOneAndIsFirstShouldProduceEquivalentLocators() {
        By byIndex = Locator.hasTagName("div").hasIndex(1).build();
        By byFirst = Locator.hasTagName("div").isFirst().build();
        // Both should produce an expression ending in [1]
        Assert.assertEquals(byIndex.toString(), byFirst.toString(),
                "hasIndex(1) and isFirst() should generate the same locator string");
    }

    // ─── XpathAxis methods ─────────────────────────────────────────────────────

    @Test(description = "byAxis().followingSibling: xpath should contain following-sibling axis")
    public void xpathAxisFollowingSiblingShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("label")
                .byAxis().followingSibling("input")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("following-sibling") && str.contains("input"),
                "Built locator must include the following-sibling:: axis and target tag");
    }

    @Test(description = "byAxis().precedingSibling: xpath should contain preceding-sibling axis")
    public void xpathAxisPrecedingSiblingShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("span")
                .byAxis().precedingSibling("div")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("preceding-sibling"),
                "Built locator must include the preceding-sibling:: axis");
    }

    @Test(description = "byAxis().ancestor: xpath should contain ancestor axis")
    public void xpathAxisAncestorShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("td")
                .byAxis().ancestor("table")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("ancestor") && locator.toString().contains("table"),
                "Built locator must include the ancestor:: axis and the target tag");
    }

    @Test(description = "byAxis().parent: xpath should contain parent axis")
    public void xpathAxisParentShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("li")
                .byAxis().parent("ul")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("parent"),
                "Built locator must include the parent:: axis");
    }

    @Test(description = "byAxis().descendant: xpath should contain descendant axis")
    public void xpathAxisDescendantShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("nav")
                .byAxis().descendant("a")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("descendant") && locator.toString().contains("a"),
                "Built locator must include the descendant:: axis");
    }

    @Test(description = "byAxis().following: xpath should contain following axis")
    public void xpathAxisFollowingShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("h2")
                .byAxis().following("p")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("following"),
                "Built locator must include the following:: axis");
    }

    @Test(description = "byAxis().preceding: xpath should contain preceding axis")
    public void xpathAxisPrecedingShouldContainAxisInExpression() {
        By locator = Locator.hasTagName("footer")
                .byAxis().preceding("header")
                .build();
        Assert.assertNotNull(locator, "Locator should not be null");
        Assert.assertTrue(locator.toString().contains("preceding"),
                "Built locator must include the preceding:: axis");
    }

    // ─── Locator.hasRole(Role) ─────────────────────────────────────────────────

    @Test(description = "Locator.hasRole(BUTTON): locator should contain button element expression")
    public void locatorHasRoleButtonShouldContainButtonXpath() {
        By locator = Locator.hasRole(Role.BUTTON).build();
        Assert.assertNotNull(locator, "Role-based locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("button") || str.contains("input"),
                "BUTTON role locator should reference button or input elements");
    }

    @Test(description = "Locator.hasRole(LINK): locator should reference anchor elements")
    public void locatorHasRoleLinkShouldContainAnchorExpression() {
        By locator = Locator.hasRole(Role.LINK).build();
        Assert.assertNotNull(locator, "LINK role locator should not be null");
        Assert.assertTrue(locator.toString().contains("a") || locator.toString().contains("link"),
                "LINK role locator should reference anchor elements");
    }

    @Test(description = "Locator.hasRole(TEXTBOX): locator should reference input or textarea elements")
    public void locatorHasRoleTextboxShouldContainInputOrTextarea() {
        By locator = Locator.hasRole(Role.TEXTBOX).build();
        Assert.assertNotNull(locator, "TEXTBOX role locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("input") || str.contains("textarea"),
                "TEXTBOX role locator should reference input or textarea elements");
    }

    @Test(description = "Locator.hasRole(CHECKBOX): locator should reference checkbox input")
    public void locatorHasRoleCheckboxShouldContainCheckbox() {
        By locator = Locator.hasRole(Role.CHECKBOX).build();
        Assert.assertNotNull(locator, "CHECKBOX role locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("checkbox") || str.contains("input"),
                "CHECKBOX role locator should reference checkbox inputs");
    }

    @Test(description = "Locator.hasRole(TABLE): locator should reference table elements")
    public void locatorHasRoleTableShouldContainTableExpression() {
        By locator = Locator.hasRole(Role.TABLE).build();
        Assert.assertNotNull(locator, "TABLE role locator should not be null");
        Assert.assertTrue(locator.toString().contains("table"),
                "TABLE role locator should reference table elements");
    }

    @Test(description = "Locator.hasRole(HEADING): locator should reference heading elements")
    public void locatorHasRoleHeadingShouldContainHeadingExpression() {
        By locator = Locator.hasRole(Role.HEADING).build();
        Assert.assertNotNull(locator, "HEADING role locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("h1") || str.contains("h2") || str.contains("h3"),
                "HEADING role locator should reference h1-h6 elements");
    }

    // ─── Role enum completeness ────────────────────────────────────────────────

    @Test(description = "Role enum should include all 14 expected constants")
    public void roleEnumShouldHaveFourteenConstants() {
        Assert.assertEquals(Role.values().length, 14,
                "Role enum should declare 14 ARIA role constants");
    }

    @Test(description = "All Role constants should produce non-null locators when used with hasRole()")
    public void allRoleConstantsShouldProduceNonNullLocators() {
        for (Role role : Role.values()) {
            By locator = Locator.hasRole(role).build();
            Assert.assertNotNull(locator,
                    "Role " + role.name() + " should produce a non-null locator");
            LocatorBuilder.cleanup();
        }
    }

    @Test(description = "All Role constants should produce non-empty locator strings")
    public void allRoleConstantsShouldProduceNonEmptyLocatorStrings() {
        for (Role role : Role.values()) {
            String str = Locator.hasRole(role).build().toString();
            Assert.assertFalse(str.isBlank(),
                    "Role " + role.name() + " should produce a non-empty locator expression");
            LocatorBuilder.cleanup();
        }
    }

    // ─── combined attribute chaining with axis ─────────────────────────────────

    @Test(description = "Axis followed by attribute predicate should produce compound expression")
    public void axisThenAttributePredicateShouldProduceCompoundExpression() {
        By locator = Locator.hasTagName("label")
                .byAxis().followingSibling("input")
                .hasAttribute("type", "text")
                .build();
        Assert.assertNotNull(locator, "Compound axis+attribute locator should not be null");
        String str = locator.toString();
        Assert.assertTrue(str.contains("following-sibling"),
                "Expression should still contain the axis fragment");
        Assert.assertTrue(str.contains("text"),
                "Expression should contain the attribute value predicate");
    }
}
