# https://github.com/aerokube/selenoid/blob/master/docs/docker-compose.adoc#selenoid-with-docker-compose
# http://aerokube.com/images/latest/#_browser_image_information
# Start by uncommenting what you need from under the "Browser Images" section below
# Then download all the needed docker-images by running this command `docker-compose -f selenoid_setup.yml pull`
# Once done, you can move to use selenoid.yml
# You can rerun these steps at anytime to update to the latest container versions
## visit browsers.json for more info on browser configurations: https://github.com/aerokube/selenoid/blob/master/docs/browsers-configuration-file.adoc
version: '3'
services:
  selenoid:
    image: aerokube/selenoid:latest-release
  selenoid-ui:
    image: aerokube/selenoid-ui:latest-release
# Browser Images
#  firefox:
#    image: selenoid/firefox:latest
#  chrome:
#    image: selenoid/chrome:latest
#  chrome-mobile:
#    image: selenoid/chrome-mobile:86.0
#  edge:
#    image: browsers/edge:latest
#  safari:
#    image: browsers/safari:15.0
#  android:
#    image: browsers/android:latest