package com.shaft.intellij.settings;

import com.intellij.openapi.options.Configurable;
import com.intellij.openapi.options.ConfigurationException;
import com.intellij.ui.components.JBCheckBox;
import com.intellij.ui.components.JBTextField;
import com.intellij.util.ui.FormBuilder;
import org.jetbrains.annotations.Nls;
import org.jetbrains.annotations.Nullable;

import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JComboBox;
import javax.swing.JComponent;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JPasswordField;
import java.util.Arrays;
import java.util.Objects;

/**
 * Settings page for SHAFT IntelliJ integration.
 */
public final class ShaftSettingsConfigurable implements Configurable {
    private JPanel panel;
    private JBTextField mcpCommand;
    private JComboBox<String> defaultClient;
    private JComboBox<String> defaultMode;
    private JBCheckBox passProviderKeys;
    private JPasswordField openAiKey;
    private JPasswordField anthropicKey;
    private JPasswordField githubKey;

    @Override
    public @Nls String getDisplayName() {
        return "SHAFT";
    }

    @Override
    public @Nullable JComponent createComponent() {
        mcpCommand = new JBTextField();
        mcpCommand.getEmptyText().setText("java -jar path/to/shaft-mcp.jar stdio");
        mcpCommand.getAccessibleContext().setAccessibleName("MCP stdio command");
        defaultClient = new JComboBox<>(model("CODEX", "CLAUDE_CODE", "COPILOT_CLI"));
        defaultClient.getAccessibleContext().setAccessibleName("Default assistant client");
        defaultMode = new JComboBox<>(model("ASK", "PLAN", "AGENT"));
        defaultMode.getAccessibleContext().setAccessibleName("Default assistant mode");
        passProviderKeys = new JBCheckBox("Pass stored provider keys to SHAFT MCP environment");
        openAiKey = new JPasswordField();
        openAiKey.getAccessibleContext().setAccessibleName("OpenAI API key");
        anthropicKey = new JPasswordField();
        anthropicKey.getAccessibleContext().setAccessibleName("Anthropic API key");
        githubKey = new JPasswordField();
        githubKey.getAccessibleContext().setAccessibleName("GitHub API key");

        panel = FormBuilder.createFormBuilder()
                .addComponent(section("MCP"))
                .addLabeledComponent(label("MCP stdio command", 'M', mcpCommand), mcpCommand)
                .addComponent(help("Generated by the SHAFT MCP installer; used for Assistant and Tools requests."))
                .addComponent(section("Assistant"))
                .addLabeledComponent(label("Default assistant client", 'C', defaultClient), defaultClient)
                .addLabeledComponent(label("Default assistant mode", 'D', defaultMode), defaultMode)
                .addComponent(help("The Assistant tab is always available. Agent mode still requires explicit source mutation approval per request."))
                .addComponent(section("Provider keys"))
                .addComponent(passProviderKeys)
                .addLabeledComponent(label("OpenAI API key", 'O', openAiKey), openAiKey)
                .addLabeledComponent(label("Anthropic API key", 'A', anthropicKey), anthropicKey)
                .addLabeledComponent(label("GitHub API key", 'G', githubKey), githubKey)
                .addComponentFillVertically(new JPanel(), 0)
                .getPanel();
        reset();
        return panel;
    }

    @Override
    public boolean isModified() {
        ShaftSettingsState.Settings state = ShaftSettingsState.getInstance().getState();
        return !Objects.equals(state.mcpCommand, mcpCommand.getText())
                || !Objects.equals(state.defaultAutobotClient, defaultClient.getSelectedItem())
                || !Objects.equals(state.defaultAutobotMode, defaultMode.getSelectedItem())
                || state.passProviderApiKeysToMcp != passProviderKeys.isSelected()
                || hasPassword(openAiKey)
                || hasPassword(anthropicKey)
                || hasPassword(githubKey);
    }

    @Override
    public void apply() throws ConfigurationException {
        ShaftSettingsState.Settings state = ShaftSettingsState.getInstance().getState();
        state.mcpCommand = mcpCommand.getText().trim();
        state.defaultAutobotClient = String.valueOf(defaultClient.getSelectedItem());
        state.defaultAutobotMode = String.valueOf(defaultMode.getSelectedItem());
        state.passProviderApiKeysToMcp = passProviderKeys.isSelected();

        ShaftCredentialService credentials = ShaftCredentialService.getInstance();
        saveIfPresent(credentials, "OPENAI_API_KEY", openAiKey);
        saveIfPresent(credentials, "ANTHROPIC_API_KEY", anthropicKey);
        saveIfPresent(credentials, "GITHUB_TOKEN", githubKey);
    }

    @Override
    public void reset() {
        ShaftSettingsState.Settings state = ShaftSettingsState.getInstance().getState();
        mcpCommand.setText(state.mcpCommand);
        defaultClient.setSelectedItem(state.defaultAutobotClient);
        defaultMode.setSelectedItem(state.defaultAutobotMode);
        passProviderKeys.setSelected(state.passProviderApiKeysToMcp);
        clear(openAiKey);
        clear(anthropicKey);
        clear(githubKey);
    }

    @Override
    public void disposeUIResources() {
        panel = null;
        mcpCommand = null;
        defaultClient = null;
        defaultMode = null;
        passProviderKeys = null;
        openAiKey = null;
        anthropicKey = null;
        githubKey = null;
    }

    private static ComboBoxModel<String> model(String... values) {
        return new DefaultComboBoxModel<>(values);
    }

    private static JLabel section(String text) {
        JLabel label = new JLabel(text);
        label.getAccessibleContext().setAccessibleName(text + " settings section");
        return label;
    }

    private static JLabel help(String text) {
        JLabel label = new JLabel(text);
        label.setEnabled(false);
        return label;
    }

    private static JLabel label(String text, char mnemonic, JComponent target) {
        JLabel label = new JLabel(text);
        label.setDisplayedMnemonic(mnemonic);
        label.setLabelFor(target);
        return label;
    }

    private static boolean hasPassword(JPasswordField field) {
        return field != null && field.getPassword().length > 0;
    }

    private static void saveIfPresent(ShaftCredentialService credentials, String key, JPasswordField field) {
        char[] password = field.getPassword();
        if (password.length > 0) {
            credentials.setApiKey(key, password);
            clear(field);
        }
    }

    private static void clear(JPasswordField field) {
        char[] password = field.getPassword();
        Arrays.fill(password, '\0');
        field.setText("");
    }
}
