package com.shaft.mcp;

import com.shaft.capture.guardrail.GeneratedCodeGuardrails;
import com.shaft.capture.guardrail.GuardrailCheckResult;
import com.shaft.capture.guardrail.GuardrailViolation;
import com.shaft.capture.model.ElementSnapshot;
import com.shaft.capture.model.LocatorCandidate;
import org.junit.jupiter.api.Test;

import java.util.List;
import java.util.Map;
import java.util.Set;

import static org.junit.jupiter.api.Assertions.assertEquals;
import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

/**
 * Issue #4279: {@link BrowserService#locatorCode} must never emit a raw
 * {@code SHAFT.GUI.Locator.id/name/cssSelector(...)} factory -- exactly the form
 * {@code GeneratedCodeGuardrails}' {@code NON_ARIA_LOCATOR} rule (ERROR severity) bans -- and its
 * {@code ID}-strategy tier-1 decision must match {@code LocatorPolicy}'s real tier logic (unique,
 * stable, non-autogenerated, no stray quote), not unconditionally emit {@code hasId(...)}.
 */
class BrowserServiceLocatorCodeTest {
    private static ElementSnapshot snapshot(String tagName, String role, String accessibleName, String label) {
        return new ElementSnapshot("logical-1", tagName, role, accessibleName, label,
                Map.of(), List.of(), true, true, false);
    }

    private static LocatorCandidate candidate(
            LocatorCandidate.LocatorStrategy strategy, String expression, int uniquenessCount, boolean stable) {
        return new LocatorCandidate(strategy, expression, uniquenessCount, true, stable, Set.of());
    }

    private static LocatorCandidate roleCandidate(String expression, boolean roleXpathVerified) {
        return new LocatorCandidate(LocatorCandidate.LocatorStrategy.ROLE, expression, 1, true, true,
                Set.of(), "", roleXpathVerified);
    }

    @Test
    void uniqueStableAuthoredIdEmitsLocatorBuilderHasId() {
        LocatorCandidate id = candidate(LocatorCandidate.LocatorStrategy.ID, "login-button", 1, true);
        String code = BrowserService.locatorCode(id, snapshot("button", "", "", ""));
        assertEquals("SHAFT.GUI.Locator.hasAnyTagName().hasId(\"login-button\").build()", code);
    }

    @Test
    void autoGeneratedIdShapeDoesNotEmitHasId() {
        LocatorCandidate id = candidate(LocatorCandidate.LocatorStrategy.ID, "mat-input-3", 1, true);
        String code = BrowserService.locatorCode(id, snapshot("input", "", "", ""));
        assertFalse(code.contains(".hasId("), code);
        assertEquals("SHAFT.GUI.Locator.hasTagName(\"input\").hasAttribute(\"aria-label\", \"mat-input-3\").build()",
                code);
    }

    @Test
    void nonUniqueIdDoesNotEmitHasId() {
        LocatorCandidate id = candidate(LocatorCandidate.LocatorStrategy.ID, "generic-input", 2, true);
        String code = BrowserService.locatorCode(id, snapshot("input", "", "", ""));
        assertFalse(code.contains(".hasId("), code);
    }

    @Test
    void idWithQuoteCharacterDoesNotEmitHasId() {
        LocatorCandidate id = candidate(LocatorCandidate.LocatorStrategy.ID, "foo\"bar", 1, true);
        String code = BrowserService.locatorCode(id, snapshot("input", "", "", ""));
        assertFalse(code.contains(".hasId("), code);
    }

    @Test
    void verifiedRoleWithMappableRoleStillEmitsHasRoleBuilder() {
        // ROLE rendering is intentionally left untouched by this fix (decision: keep BrowserService's
        // own ariaRole()+hasRole() path rather than route through LocatorPolicy.plan, since
        // BrowserService never sets roleXpathVerified=true -- it has no live-DOM verification
        // capability, only a static Jsoup parse -- so routing ROLE through LocatorPolicy.plan would
        // make tier 2 permanently unreachable here and regress every role-only recommendation).
        LocatorCandidate role = roleCandidate("button:Sign in", true);
        String code = BrowserService.locatorCode(role, snapshot("button", "button", "Sign in", ""));
        assertEquals("SHAFT.GUI.Locator.hasRole(Role.BUTTON).build()", code);
    }

    @Test
    void unmappableRoleFallsThroughToGenericBuilder() {
        LocatorCandidate role = roleCandidate("searchbox:Search", true);
        String code = BrowserService.locatorCode(role, snapshot("div", "searchbox", "Search", ""));
        assertFalse(code.contains(".hasRole("), code);
    }

    @Test
    void testIdStrategyNeverEmitsRawCssSelectorFactory() {
        LocatorCandidate testId = candidate(LocatorCandidate.LocatorStrategy.TEST_ID,
                "[data-testid=\"submit\"]", 1, true);
        String code = BrowserService.locatorCode(testId, snapshot("button", "", "", ""));
        assertFalse(code.contains("SHAFT.GUI.Locator.cssSelector("), code);
    }

    @Test
    void cssStrategyNeverEmitsRawCssSelectorFactory() {
        LocatorCandidate css = candidate(LocatorCandidate.LocatorStrategy.CSS, ".submit-button", 1, true);
        String code = BrowserService.locatorCode(css, snapshot("button", "", "", ""));
        assertFalse(code.contains("SHAFT.GUI.Locator.cssSelector("), code);
    }

    @Test
    void nameStrategyNeverEmitsRawNameFactory() {
        LocatorCandidate name = candidate(LocatorCandidate.LocatorStrategy.NAME, "email", 1, true);
        String code = BrowserService.locatorCode(name, snapshot("input", "", "", ""));
        assertFalse(code.contains("SHAFT.GUI.Locator.name("), code);
    }

    @Test
    void everyStrategyOutputClearsTheNonAriaLocatorGuardrail() {
        ElementSnapshot target = snapshot("button", "button", "Sign in", "");
        List<LocatorCandidate> candidates = List.of(
                candidate(LocatorCandidate.LocatorStrategy.ID, "login-button", 1, true),
                candidate(LocatorCandidate.LocatorStrategy.ID, "mat-input-3", 1, true),
                candidate(LocatorCandidate.LocatorStrategy.ID, "generic-input", 2, true),
                candidate(LocatorCandidate.LocatorStrategy.TEST_ID, "[data-testid=\"submit\"]", 1, true),
                candidate(LocatorCandidate.LocatorStrategy.CSS, ".submit-button", 1, true),
                candidate(LocatorCandidate.LocatorStrategy.NAME, "email", 1, true),
                roleCandidate("button:Sign in", true),
                roleCandidate("searchbox:Search", true),
                candidate(LocatorCandidate.LocatorStrategy.XPATH,
                        "//button[normalize-space(.)='Sign in']", 1, false));

        for (LocatorCandidate candidate : candidates) {
            String code = BrowserService.locatorCode(candidate, target);
            GuardrailCheckResult result = GeneratedCodeGuardrails.check(code);
            boolean bannedFactory = result.violations().stream()
                    .map(GuardrailViolation::kind)
                    .anyMatch("NON_ARIA_LOCATOR"::equals);
            assertFalse(bannedFactory, candidate.strategy() + " -> " + code);
        }
    }
}
