name: E2E LambdaTest Tests

on:
  workflow_dispatch:

jobs:
  LambdaTest_NativeAndroid:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          node-version: '16'
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=lambdatest" "-DgenerateAllureReportArchive=true" "-Dtest=%regex[.*Test_LTMobAPK*.*]"
      - name: Post-Test Report and Check
        if: always()
        uses: ./.github/actions/post-test-report
        with:
          job-name: LambdaTest_NativeAndroid
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  LambdaTest_NativeIOS:
    runs-on: ubuntu-latest
    needs: [ LambdaTest_NativeAndroid ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          node-version: '16'
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=lambdatest" "-DgenerateAllureReportArchive=true" "-Dtest=%regex[.*Test_LTMobIPA*.*]"
      - name: Post-Test Report and Check
        if: always()
        uses: ./.github/actions/post-test-report
        with:
          job-name: LambdaTest_NativeIOS
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  LambdaTest_WebApp:
    runs-on: ubuntu-latest
    needs: [ LambdaTest_NativeAndroid, LambdaTest_NativeIOS ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          node-version: '16'
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=lambdatest" "-DgenerateAllureReportArchive=true" "-Dtest=%regex[.*Test_LTWebApp*.*]"
      - name: Post-Test Report and Check
        if: always()
        uses: ./.github/actions/post-test-report
        with:
          job-name: LambdaTest_WebApp
          codecov-token: ${{ secrets.CODECOV_TOKEN }}

  LambdaTest_DesktopWeb:
    runs-on: ubuntu-latest
    needs: [ LambdaTest_NativeAndroid, LambdaTest_NativeIOS, LambdaTest_WebApp ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6
      - name: Setup Test Environment
        uses: ./.github/actions/setup-test-env
        with:
          node-version: '16'
      - name: Run tests
        continue-on-error: true
        run: mvn -e test "-DdefaultElementIdentificationTimeout=5" "-DretryMaximumNumberOfAttempts=1" "-DexecutionAddress=lambdatest" "-DgenerateAllureReportArchive=true" "-Dtest=%regex[.*Test_LTDesktopWeb*.*]"
      - name: Post-Test Report and Check
        if: always()
        uses: ./.github/actions/post-test-report
        with:
          job-name: LambdaTest_DesktopWeb
          codecov-token: ${{ secrets.CODECOV_TOKEN }}