name: MacOS - Test Artifacts Desktop Browsers Tests

on: workflow_dispatch

jobs:
  browser:
    name: Run Browser-based Tests
    runs-on: [macOS-latest]

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: Run tests on MacOS
        continue-on-error: true
        run: mvn test -DexecutionAddress="browserstack" -DtargetOperatingSystem="Mac-64" -DmaximumPerformanceMode="1" -DtargetBrowserName="Safari" "-DbrowserStack.os=OS X" "-DbrowserStack.osVersion=Monterey" "-DbrowserStack.browserVersion=15.3" -DgenerateAllureReportArchive="true" -Dtest="testPackage01.SHAFTWizard.Test_Wizard_GUI"

      - name: Check Directory Files
        run: ls -l

      - name: Upload Allure Report as Pipeline Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Allure Report
          path: "generatedReport_*.zip"

      - name: Upload Extent Report as Pipeline Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ runner.os }} - Desktop Browsers Tests Extent Report
          path: "extent-reports/ExtentReports_*.html"